version: '3'

volumes:
  postgres_data: {}
  postgres_data_backups: {}
  app-data-server: {}

services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/docker-entrypoint-initdb.d
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "9432:5432"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app-data-server:/usr/src/app/
    depends_on:
      - postgres
    env_file:
      - ./.envs/.local/.base
    ports:
      - "8080:8080"
