version: '3.8'


services:
  postgres:
    image: postgres:12-alpine
    env_file:
      - ./.envs/.local/.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE_NAME: postgres
    ports:
      - "9432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./.envs/.local/.base
    ports:
      - "8080:8080"
