"""init

Revision ID: abaf53ae7b5b
Revises: 
Create Date: 2024-01-08 23:54:46.922691

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from config.settings import POSTGRES_SCHEMA

# revision identifiers, used by Alembic.
revision: str = 'abaf53ae7b5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('date_published', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=POSTGRES_SCHEMA
    )
    op.create_index(op.f('ix_library_book_author'), 'book', ['author'], unique=False, schema=POSTGRES_SCHEMA)
    op.create_index(op.f('ix_library_book_date_published'), 'book', ['date_published'], unique=False, schema=POSTGRES_SCHEMA)
    op.create_index(op.f('ix_library_book_genre'), 'book', ['genre'], unique=False, schema=POSTGRES_SCHEMA)
    op.create_index(op.f('ix_library_book_id'), 'book', ['id'], unique=False, schema=POSTGRES_SCHEMA)
    op.create_index(op.f('ix_library_book_name'), 'book', ['name'], unique=False, schema=POSTGRES_SCHEMA)
    op.create_table('book_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('origin_file_name', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], [f'{POSTGRES_SCHEMA}.book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema=POSTGRES_SCHEMA
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_file', schema=POSTGRES_SCHEMA)
    op.drop_index(op.f('ix_library_book_name'), table_name='book', schema=POSTGRES_SCHEMA)
    op.drop_index(op.f('ix_library_book_id'), table_name='book', schema=POSTGRES_SCHEMA)
    op.drop_index(op.f('ix_library_book_genre'), table_name='book', schema=POSTGRES_SCHEMA)
    op.drop_index(op.f('ix_library_book_date_published'), table_name='book', schema=POSTGRES_SCHEMA)
    op.drop_index(op.f('ix_library_book_author'), table_name='book', schema=POSTGRES_SCHEMA)
    op.drop_table('book', schema=POSTGRES_SCHEMA)
    # ### end Alembic commands ###
